### ISSUE TITLE
qt-xcb removed

### ISSUE THREAD

**Issue by haampie** [darkmattercoder/qt-build#5]
This is more of a question than an issue: why was the `-qt-xcb` flag removed from 5.12.1 and onwards? I'm using a deployment tool that assumes `plugins/platforms/libqxcb.so` exists.

**Comment by darkmattercoder** [comment]
If I remember right, it did not build with that and I needed a working build. if you have a bit of spare time, you could use the local build script to have a look at it and try to make it work again with the xcb config. 

I'll try it myself as well to give you further feedback.

**Comment by darkmattercoder** [comment]
Well,

configuring `5.12.1` with `-qt-xcb` fails with `ERROR: Feature 'xcb' was enabled, but the pre-condition 'features.thread && features.xkbcommon && libs.xcb' failed.`

I suspect that the system libs for xcb-dev in the used ubuntu image might not be compatible anymore with 5.12.1 and onwards, but I did not find any info on that, so it's just a rough guess...

**Comment by somlioy** [comment]
I'm assuming @haampie is talking about linuxdeployqt. I have also tried to use that in 5.12.6 without success due to missing libqxcb.so. The solution was install dependencies for Qt automatically as such 

`apt-get -y build-dep qtbase-opensource-src`
`apt-get -y install libxcb-xinerama0-dev`
`apt-get -y install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev`

(See: https://wiki.qt.io/Building_Qt_5_from_Git)

Sources also has to be updated **before** doing build-dep;
(See: https://askubuntu.com/a/857433)

`cp /etc/apt/sources.list /etc/apt/sources.list~`
`sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list`
`apt-get update`

-qt-xcb can then be appended to ./configure again

Heres another way to install dependencies: https://gist.github.com/jinahya/5ac86a70b190abed14d8


It would also be nice to bundle linuxdeployqt with the Docker images. Linuxdeployqt also requires patchelf:
`curl -sLO https://ftp.fau.de/debian/pool/main/p/patchelf/patchelf_0.8-2_amd64.deb`
`dpkg -i patchelf_0.8-2_amd64.deb`

Newer patchelf versions apparantly cripples libQt5Core; https://github.com/NixOS/patchelf/issues/124

Building linuxdeployqt
`git clone https://github.com/probonopd/linuxdeployqt.git`
`cd linuxdeployqt && qmake && make && make install`

**Comment by haampie** [comment]
Yeah, you don't event need `libxcb-xinerama0-dev`.

Just sharing my recent Dockerfile for building Qt that works well:

https://gist.github.com/haampie/8acbefcdd0f9891e0a3c762f660aeba4

There's a couple superfluous packages being installed there (e.g. hdf5-dev), but I needed those for another dependency not show here.

@somlioy I'm using https://github.com/linuxdeploy/linuxdeploy-plugin-qt for deployment

**Comment by haampie** [comment]
A few packages I have installed that seem sensible but are missing in this repo are

```
libxkbcommon-x11-dev # this one is required for the xcb plugin.

libglu1-mesa-dev # opengl stuff, not sure if necessary
libegl1-mesa # opengl stuff, not sure if necessary
libxt-dev # not sure what this is
libfuse2 # in case you want to create appimages
```

**Comment by darkmattercoder** [comment]
Hi,
thank you for your PR. I wonder wether the configuration was necessary at all since I changed the base image from ubuntu 16.04 to ubuntu 18.04 a few days ago and did not recheck wether that update would have been also able to allow the flag again. However, I will include that pr most likely in the next days. As for the suggestion of `linuxdeployqt`, I also will consider adding that.

**Comment by haampie** [comment]
Just fyi, `libxkbcommon-x11-dev` was necessary on my Ubuntu 18.04 build, I have seen that same configure error message this month :). It cannot hurt to add it

**Comment by darkmattercoder** [comment]
I still have an erroneous build for 5.13.1, but I assume that was only a VM failure in the build pipeline. Once succeeded, this will be closed
